In [5]:
import numpy as np
from numpy import linalg as LA
from itertools import combinations
np.set_printoptions(precision=5, suppress=True)

In [6]:
def colinear(p1, p2, p3):
    matrix = np.array([p1,p2,p3]).T
    det = LA.det(matrix)

    return det == 0

In [7]:
import numpy as np
np.set_printoptions(precision=5, suppress=True)
from itertools import combinations
from numpy import linalg as LA
 
 
def naivni(origs, imgs):
    def colinear(p1, p2, p3):
        matrix = np.array([p1,p2,p3])
        det = LA.det(matrix)

        return det == 0
    
    for a,b,c in combinations(origs, 3):
        if colinear(a,b,c):
            return "Losi originali!"
    for a,b,c in combinations(imgs, 3):
        if colinear(a,b,c):
            return "Lose slike!"

    d0 = np.array(origs[3])
    d = np.array(imgs[3])

    #prvo preslikavanje
    A = np.array(origs[:-1])
    P = LA.solve(A.T, d0.T)

    f = P * A.T
    f = np.array(f)
    print(f)

    #drugo preslikavanje
    B = np.array(imgs[:-1])
    P2 = LA.solve(B.T, d.T)

    g = P2 * B.T 
    g = np.array(g)
    print(g)

    matrica = g @ LA.inv(f)
    matrica = np.array(matrica)/matrica[-1][-1]
    matrica = [np.where(np.isclose(x,0), 0.0, x) for x in matrica]
    
    return np.array(matrica)

In [8]:
trapez = [[0, 0, 1], [2, 0, 1], [1, 1, 1], [0, 1, 1]] 
pravougaonik = [[0, 0, 1], [1, 0, 1], [1, 1, 1], [0, 1, 1]]
print(naivni(trapez, pravougaonik))

[[ 0.  -1.   1. ]
 [ 0.  -0.   1. ]
 [ 0.5 -0.5  1. ]]
[[ 0. -1.  1.]
 [ 0. -0.  1.]
 [ 1. -1.  1.]]
[[ 0.5  0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.  -0.5  1. ]]
