In [48]:
import numpy as np
from numpy import linalg as LA
np.set_printoptions(precision=5, suppress=True)

In [3]:
def afinize(x):
    return x/x[-1]

In [43]:
def normMatrix(points):
    def afinize(x):
        return x/x[-1]
    
    aPts = [afinize(np.array(pt)) for pt in points]
    cog = np.mean(aPts, axis = 0)

    translated = aPts - cog
    G = np.array([[1, 0, -cog[0]], [0, 1, -cog[1]], [0, 0, 1]])

    norms = [LA.norm(pt) for pt in translated]
    avgNorm = np.mean(norms)
    l = np.sqrt(2)/avgNorm
    S = np.array([[l, 0, 0], [0, l, 0], [0, 0, 1]])
    
    return np.array(S@G)

In [56]:
def DLT(org: list, img: list):
    if len(org) != len(img):
        return "Razlicit broj tacaka u slici i originalu!"

    #dve jednacine i pravljenje 2nx9 matrice
    A = []
    for (x1, x2, x3), (xp1, xp2, xp3) in zip(org, img):
        A.append([0, 0, 0, -1*xp3*x1, -1*xp3*x2, -1*xp3*x3, xp2*x1, xp2*x2, xp2*x3])
        A.append([xp3*x1, xp3*x2, xp3*x3, 0, 0, 0, -1*xp1*x1, -1*xp1*x2, -1*xp1*x3])
    A = np.array(A)

    U, D, V = LA.svd(A)
    P = V[-1].reshape(3,3)
    P = P/P[-1,-1]

    return np.array(P)

In [57]:
def DLTwithNormalization(org, img):
    org = np.array(org)
    img = np.array(img)
    
    T1 = normMatrix(org)
    nOrg = T1 @ org.T
    
    T2 = normMatrix(img)
    nImg = T2 @ img.T

    P2 = DLT(nOrg.T, nImg.T)
    P1 = LA.inv(T2) @ P2 @ T1
    P1 = P1/P1[-1,-1]

    return np.array(P1)

In [58]:
a0 = [-3,-1,1]
b0 = [3,-1,1]
c0 = [1,1,1]
d0 = [-1,1,1]

a = [-2,-1,1]
b = [2,-1,1]
c = [2,1,1]
d = [-2,1,1]

f1 = np.array([a0,b0,c0,d0])
f2 = np.array([a,b,c,d])

normalizedDLT(f1, f2)

array([[ 1. , -0. , -0. ],
       [-0. ,  1. , -0.5],
       [-0. , -0.5,  1. ]])

In [59]:
trapez = [[- 3, - 1, 1], [3, - 1, 1], [1, 1, 1], [- 1, 1, 1], [1,2,3], [-8,-2,1]] 
print(normMatrix(trapez))


[[0.44969 0.      0.5746 ]
 [0.      0.44969 0.09993]
 [0.      0.      1.     ]]


In [54]:
trapez = [[- 3, - 1, 1], [3, - 1, 1], [1, 1, 1], [- 1, 1, 1], [1,2,3], [-8,-2,1]] 
pravougaonik1 = [[- 2, - 1, 1], [2, - 1, 1], [2, 1, 1], [- 2, 1, 1], [2,1,5], [-16,-5,5]]
print(DLTwithNormalization(trapez, pravougaonik1))

[[ 0.99732  0.16288 -0.19592]
 [ 0.02538  0.96398 -0.52775]
 [-0.07202 -0.53967  1.     ]]
